pipeline {
  agent any
  tools {
      jdk 'java-11'
      maven 'maven'
  }
  stages {
       stage('Install') {
            steps {
                sh "mvn clean install"           
            }           
        post {
            always {
                junit '**/target/*-reports/TEST-*.xml'
            }           
        }       
    }   
  } 
}

