pipeline {
  agent any
  tools {
      jdk 'java-11'
      maven 'maven'
  }
  stages {
      stage('Install') {
	  steps {
              dir('your-sub-directory'){
                  sh "$PWD"
              }       
	  }
          steps {
              sh 'mvn clean install'               
          }
	  post {
	      always {
                   junit '**/target/*-reports/TEST-*.xml'               
	      }
	  }
      }
  }
}

